STOCKS_DATA = {
    # Panel Líder
    "ALUA": {"sector": "Materials", "panel": "Líder"},
    "BBAR": {"sector": "Financial", "panel": "Líder"},
    "BMA": {"sector": "Financial", "panel": "Líder"},
    "BYMA": {"sector": "Market", "panel": "Líder"},
    "CEPU": {"sector": "Energy", "panel": "Líder"},
    "COME": {"sector": "Energy", "panel": "Líder"},
    "CRES": {"sector": "Real Estate", "panel": "Líder"},
    "CVH": {"sector": "Communication", "panel": "Líder"},
    "EDN": {"sector": "Energy", "panel": "Líder"},
    "GGAL": {"sector": "Financial", "panel": "Líder"},
    "LOMA": {"sector": "Materials", "panel": "Líder"},
    "METR": {"sector": "Financial", "panel": "Líder"},
    "MIRG": {"sector": "Financial", "panel": "Líder"},
    "PAMP": {"sector": "Energy", "panel": "Líder"},
    "SUPV": {"sector": "Financial", "panel": "Líder"},
    "TECO2": {"sector": "Communication", "panel": "Líder"},
    "TGNO4": {"sector": "Gas", "panel": "Líder"},
    "TGSU2": {"sector": "Gas", "panel": "Líder"},
    "TRAN": {"sector": "Energy", "panel": "Líder"},
    "TXAR": {"sector": "Materials", "panel": "Líder"},
    "VALO": {"sector": "Market", "panel": "Líder"},
    "YPFD": {"sector": "Oil", "panel": "Líder"},
    # Panel General
    "AGRO": {"sector": "Agriculture", "panel": "General"},
    "AUSO": {"sector": "Consumer", "panel": "General"},
    "BHIP": {"sector": "Financial", "panel": "General"},
    "BOLT": {"sector": "Entertainment", "panel": "General"},
    "BPAT": {"sector": "Financial", "panel": "General"},
    "CADO": {"sector": "Agriculture", "panel": "General"},
    "CAPX": {"sector": "Energy", "panel": "General"},
    "CECO2": {"sector": "Energy", "panel": "General"},
    "CELU": {"sector": "Materials", "panel": "General"},
    "CGPA2": {"sector": "Gas", "panel": "General"},
    "CTIO": {"sector": "Real Estate", "panel": "General"},
    "DGCU2": {"sector": "Gas", "panel": "General"},
    "DYCA": {"sector": "Real Estate", "panel": "General"},
    "FERR": {"sector": "Materials", "panel": "General"},
    "GARO": {"sector": "Agriculture", "panel": "General"},
    "GBAN": {"sector": "Gas", "panel": "General"},
    "GCLA": {"sector": "Communication", "panel": "General"},
    "HARG": {"sector": "Materials", "panel": "General"},
    "INVJ": {"sector": "Agriculture", "panel": "General"},
    "IRSA": {"sector": "Real Estate", "panel": "General"},
    "LEDE": {"sector": "Agriculture", "panel": "General"},
    "LONG": {"sector": "Consumer", "panel": "General"},
    "MOLI": {"sector": "Consumer", "panel": "General"},
    "MORI": {"sector": "Consumer", "panel": "General"},
    "MTR": {"sector": "Financial", "panel": "General"},
    "OEST": {"sector": "Consumer", "panel": "General"},
    "PATA": {"sector": "Consumer", "panel": "General"},
    "SAMI": {"sector": "Agriculture", "panel": "General"},
}

START_DATE = "2017-01-01"
